### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/love-sandwiches#1]
In order to **get involved**, as a **club member**, I can **find the dates and times of meetups on the website**.

**Comment by broken-helix** [comment]
In order to **join the club**, as a **prospective member**, I can **contact the organisers through the website**.

#Acceptance Criteria
* Link to contact form in navigation bar
* Contact form asks for contact details for reply
* Default response provided to user when form is submitted 

#Task List
- [ ] Add contact us link to nav bar
- [ ] Add two email entry forms to contact form which must match
- [ ] Add confirmation message when user presses submit
